# MQTT Broker configuration
MQTT_BROKER_ADRESS      = '127.0.0.1' # Acer Laptop IP address # Ip adress (Fred router) 192.168.99.100
MQTT_PORT               = 1883

ROBOT_PACKAGE_FOLDER    = 'robot_package' # Directory with robot modules

TERMINAL_BASE_TOPIC    = 'TERMINAL' 

# Robot Affective State Topic
ROBOT_AFFECTIVE_STATE_TOPIC = 'ROBOT_AFFECTIVE_STATE'

# User Affective State Topic
USER_AFFECTIVE_STATE_TOPIC = 'USER_AFFECTIVE_STATE'

# Robot Behavior State Topic
ROBOT_BEHAVIOR_STATE_TOPIC = 'ROBOT_BEHAVIOR_STATE'

# Default audio file extension.
AUDIO_EXTENSION = ".wav"

# Audio format generated by IBM Watson (file extension).
WATSON_AUDIO_EXTENSION = ".mp3"
ACCEPT_AUDIO_EXTENSION = "audio/mp3"

VOICE_TYPE = "pt-BR_IsabelaV3Voice" # Default voice

# Audio generated by TTS Piper
PIPER_AUDIO_EXTENSION = ".wav"