# MQTT Broker configuration
MQTT_BROKER_ADRESS      = '127.0.0.1' # Acer Laptop IP address # Ip adress (Fred router) 192.168.99.100
MQTT_PORT               = 1883

ROBOT_PACKAGE_FOLDER    = 'robot_package' # Directory with robot modules
SIMULATOR_BASE_TOPIC    = 'SIMULATOR'
TERMINAL_BASE_TOPIC    = 'TERMINAL'

# Default audio file extension.
AUDIO_EXTENSION = ".wav"

# Audio format generated by IBM Watson (file extension).
WATSON_AUDIO_EXTENSION = ".mp3"
ACCEPT_AUDIO_EXTENSION = "audio/mp3"
