from rich import print

import re

import config # Module with network device configurations.

import robot_profile  # Module with network device configurations.

from base_command_handler import BaseCommandHandler

from ollama import chat

MODEL_LLM = "llama3.2:3b"

# MODEL_LLM = "qwen2.5:3b"


chat(
        model=MODEL_LLM,
        messages=[],
        keep_alive=-1
    )


class CommandHandler(BaseCommandHandler):

    
    def __init__(self, xml_node, communicator_obj):
        
        super().__init__(self, communicator_obj)



    def node_process(self, xml_node, memory):
        """ Node process function """


        base_topic = memory.get_base_topic()


        # Node processing
        if xml_node.text == None: # There is no text to speech
            print("[b white on red blink] FATAL ERROR [/]: [b yellow reverse] There is no instructions to prompt [/] in the element [b white]<llm>[/]. Please, check your code.✋⛔️")
            exit(1)

        instructions = xml_node.text
        palavras = instructions.split()
        texto_normalizado = ' '.join(palavras)

        # Vamos testar sem a linha abaixo para manter os enters e tabs
        # instructions = texto_normalizado.replace('\n', '').replace('\r', '').replace('\t', '') # Remove tabulações e salto de linha.
        
        # Replace variables throughout the text. variables must exist in memory
        if "#" in instructions:
            # Checks if the robot's memory (vars) is empty
            if memory.vars == {}:
                print("[b white on red blink] FATAL ERROR [/]: [b yellow reverse] No variables have been defined [/] to be used in the[b white] <talk>[/]. Please, check your code.✋⛔️")
                exit(1)

            var_list = re.findall(r'\#[a-zA-Z_]+[0-9]*', instructions) # Generate list of occurrences of vars (#...)
            for v in var_list:
                if v[1:] in memory.vars:
                    instructions = instructions.replace(v, str(memory.vars[v[1:]]))
                else:
                    # If the variable does not exist in the robot's memory, it displays an error message
                    print("[b white on red blink] FATAL ERROR [/]: The variable [b white]" + v[1:] + "[/] [b yellow reverse] has not been declared [/] to be used in the [b white]<talk>[/]. Please, check your code.✋⛔️")
                    exit(1)

        # This part replaces the $, or the $-1 or the $1 in the text
        if "$" in instructions: # Check if there is $ in the text
            # Checks if var_dollar has any value in the robot's memory
            if (len(memory.var_dollar)) == 0:
                print("[b white on red blink] FATAL ERROR [/]: There are [b yellow reverse] no values [/] for the [b white]$[/] used in the [b white]<talk>[/]. Please, check your code.✋⛔️")
                exit(1)
            else: # Find the patterns $ $n or $-n in the string and replace with the corresponding values
                dollars_list = re.findall(r'\$[-0-9]*', instructions) # Find dollar patterns and return a list of occurrences
                dollars_list = sorted(dollars_list, key=len, reverse=True) # Sort the list in descending order of length (of the element)
                for var_dollar in dollars_list:
                    if len(var_dollar) == 1: # Is the dollar ($)
                        instructions = instructions.replace(var_dollar, memory.var_dollar[-1][0])
                    else: # May be of type $n or $-n
                        if "-" in var_dollar: # $-n type
                            indice = int(var_dollar[2:]) # Var dollar is of type $-n. then just take n and convert it to int.
                            try:
                                instructions = instructions.replace(var_dollar, memory.var_dollar[-(indice + 1)][0]) 
                            except IndexError:
                                print('[b white on red blink] FATAL ERROR [/]: There was an [b yellow reverse] index error [/] for the variable [b white]"' + var_dollar + '"[/]. Please, check your code.✋⛔️')
                                exit(1)
                        else: # tipo $n
                            indice = int(var_dollar[1:]) # Var dollar is of type $n. then just take n and convert it to int.
                            try:
                                instructions = instructions.replace(var_dollar, memory.var_dollar[(indice - 1)][0])
                            except IndexError:
                                print('[b white on red blink] FATAL ERROR [/]: There was an [b yellow reverse] index error [/] for the variable [b white]"' + var_dollar + '"[/]. Please, check your code.✋⛔️')
                                exit(1)
                            

        # This part implements the random text generated by using the / character
        # instructions = instructions.split(sep="/") # Text becomes a list with the number of sentences divided by character. /
 

        print('[b white]STATE:[/] The LLM is [b green]thinking...[/]')


        memory.set_llm_messages({
            "role": "user",
            "content": instructions
        })

        response = chat(
            model=MODEL_LLM,
            messages=memory.get_llm_messages(),
            keep_alive=-1,
            options={
                "temperature": 0.3,
                "num_predict": 40,
                "repeat_penalty": 1.2
                },
            think=False
        )

        answer = response.message.content.strip()


        memory.set_llm_messages({
            "role": "assistant",
            "content": answer
        })

        print('[b white]STATE:[/] The LLM answer is: [b white]' + answer + '[/]')

        if xml_node.get("var") == None: # Maintains compatibility with the use of the $ variable
            print('[b white]STATE:[/] The LLM answer will be stored in [b white]$[/]')
            memory.setDollar([answer, "<llm>"])
        else:
            var_name = xml_node.get("var")
            print('[b white]STATE:[/] The LLM answer will be stored in [b white]' + var_name + '[/]')
            memory.setVar(var_name, answer)
        

        return xml_node # It returns the same node
        

