
ROBOT_MODEL = "EVA" # ou EVA

# You can change it if you wish to use another robot. 'EVA' (EVA), 'FRED_6793534' (FRED), 'FRED_14194525' (Frida) and FRED to (broadcasting) control all verions od FRED.
# ATTENTION: FRED's topic are automatically generated by ESP8266. It is the concatenation of FRED_(its device id).
ROBOT_BASE_TOPIC = "EVA"

SIMULATOR_BASE_TOPIC = 'SIMULATOR' # FRED virtual doesnt use a base topic like SIMULATOR. So we use a empty string (It needs to be changed)







